
EXECUTE_PROCESS(
     COMMAND ${GIT_EXEC} describe --abbrev=10
     OUTPUT_VARIABLE GIT_VERSION_AND_HASH
     OUTPUT_STRIP_TRAILING_WHITESPACE
     WORKING_DIRECTORY ${GIT_DIR}
 )

EXECUTE_PROCESS(
     COMMAND date "+%Y-%m-%d %T"
     OUTPUT_VARIABLE BUILD_TIME
     OUTPUT_STRIP_TRAILING_WHITESPACE
 )

CONFIGURE_FILE(${SRC} ${DST} @ONLY)
