#!/bin/bash
## ---------------------------------------------------------------------
##
## Copyright (C) 2012 - 2013, 2015 by the deal.II authors
##
## This file is part of the deal.II library.
##
## The deal.II library is free software; you can use it, redistribute
## it, and/or modify it under the terms of the GNU Lesser General
## Public License as published by the Free Software Foundation; either
## version 2.1 of the License, or (at your option) any later version.
## The full text of the license can be found in the file LICENSE at
## the top level of the deal.II distribution.
##
## ---------------------------------------------------------------------


if test ! -f utilities/astyle.rc ; then
  echo "*** No style file utilities/astyle.rc found."
  exit
fi

if test "`astyle --version 2>&1`" != "Artistic Style Version 2.04" ; then
  echo "*** Found a version of astyle different than the required version 2.04."
  exit
fi

# loop over all directories in which we may have source files;
# collect a list of files and then spawn a parallel process to
# indent all of them
echo "--- Indenting all source and header files"
for dir in .* ; do
  files=`find $dir | egrep '\.(cc|cpp|h)$'` ;
  if test -n "$files" ; then
    (astyle --options=utilities/astyle.rc $files ) &
  fi
done

# now wait for all of these processes to finish
wait

